### ISSUE TITLE
rosdep install drone　error

### ISSUE THREAD

**Issue by runwithyourheart** [kosmastsk/thesis#2]
When I install package drone,I encountered this error :
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
drone: Cannot locate rosdep definition for [path_planning]

Can you give me some advice to solve it? Thanks!!!

**Comment by kosmastsk** [comment]
Have you installed path_planning package?
You can find it in [here](https://github.com/kosmastsk/path_planning/tree/fa95b081eba7c51373a74b8d89ee7d2d8c40844b)
Build this first and then try again to install drone
